# **aljabar matrik**

**TIDAK MENGERJAKAN TIDAK BOLEH MASUK KELAS**
*   berikan penjelasan tentang apa itu matrik
*   operasi matrik
*   penjumlahan, perkalian, pengurangan, transpose matrik
*   buat program untuk mengalikan matrik A dan B(tidak boleh pakai @)





In [6]:
import numpy as np
import numpy as sy

In [9]:
A = np.array([[1,3,9],[3,-2,6],[9,4,1]])
B = np.array([[1,7,5],[2,4,5],[2,4,1]])
C = np.array([[3,2],[-1,2],[3,5]])
D = np.array([[3,4,7],[2,7,3],[4,1,3]])
E = A+B
F = 2*A
G = A@C
H = B@C
I = A@H
J = A@B
K = J@C

print(A)
print('\n')
print(B)
print('\n')
print(C)
print('\n')
print(D)
print('\n')
print(E)
print('\n')
print(F)
print('\n')
print(G)
print('\n')
print(H)
print('\n')
print(I)
print('\n')
print(J)
print('\n')
print(K)
print('\n')

[[ 1  3  9]
 [ 3 -2  6]
 [ 9  4  1]]


[[1 7 5]
 [2 4 5]
 [2 4 1]]


[[ 3  2]
 [-1  2]
 [ 3  5]]


[[3 4 7]
 [2 7 3]
 [4 1 3]]


[[ 2 10 14]
 [ 5  2 11]
 [11  8  2]]


[[ 2  6 18]
 [ 6 -4 12]
 [18  8  2]]


[[27 53]
 [29 32]
 [26 31]]


[[11 41]
 [17 37]
 [ 5 17]]


[[107 305]
 [ 29 151]
 [172 534]]


[[25 55 29]
 [11 37 11]
 [19 83 66]]


[[107 305]
 [ 29 151]
 [172 534]]




In [12]:
Ctrans=C.transpose()
cov=Ctrans@C
cov.shape

(2, 2)